### ISSUE TITLE
Error when setting up (MacOS 10.14.4)

### ISSUE THREAD

**Issue by nihelmasell** [joeyates/imap-backup#69] opened 2019-05-04 11:16 UTC
Hi, I get the error shown in the attached file when trying my first setup. 

If its not easily solvable please tell me the name of the configuration file I should put into the ~/.imap-backup folder

Best Regards
[imap-backup.error.txt](https://github.com/joeyates/imap-backup/files/3144285/imap-backup.error.txt)

**Comment by joeyates** [comment] 2019-05-04 17:40
@nihelmasell It looks like this is caused by a problem with the version of libreadline, for example, see [here](https://gist.github.com/zulhfreelancer/47efc39584cb9f006da43c41c014e03a#gistcomment-2819337).

Please try `nvm reinstall 2.4.0`

**Comment by nihelmasell** [comment] 2019-05-04 21:45
Hi, did you mean npm? I dont have any program named nvm. When I type npm install 2.4.0 or npm install libreadline 2.4.0, I get 404. I also tried "ln -s /usr/local/opt/readline/lib/libreadline.7.0.dylib /usr/local/opt/readline/lib/libreadline.6.dylib" like the link says, but I still can't run the setup. // What's the name of the configuration file? I can manually edit it and put it into the folder. I think its gonna be easier that way.

**Comment by joeyates** [comment] 2019-05-06 09:56
@nihelmasell Sorry `nvm` was a typo, I meant `rvm`. I see from you attachment that the Ruby you're using was installed with [rvm](https://rvm.io/)

**Comment by joeyates** [comment] 2019-05-06 09:57
@nihelmasell Info about the configuration file is available here: https://github.com/joeyates/imap-backup#configuration-file

**Comment by nihelmasell** [comment] 2019-05-09 14:16
@joeyates I tried what you said. Didn’t work. I don’t know the name of the config file. You just point at the directory in the readme.md

**Comment by joeyates** [comment] 2019-05-10 19:56
@nihelmasell The file is ` ~/.imap-backup/config.json`

**Comment by joeyates** [comment] 2019-05-14 17:07
@nihelmasell Any news on this?

**Comment by nihelmasell** [comment] 2019-05-16 20:51
@joeyates I’m on vacation. Please give me a couple days. Do I have to insert any special formatting into the Json or just paste the text chain you show in the example?

**Comment by joeyates** [comment] 2019-05-17 14:38
The README indicates the structure of the file, the details depend on your computer setup. I think you would be best of resolving the original error (of the readline library) and using the standard setup process.

**Comment by joeyates** [comment] 2019-05-24 12:57
As the problem here relates to Ruby setup, I'll close.

**Closed by joeyates** 2019-05-24 12:57 UTC
