### ISSUE TITLE
does it work for gsuite?

### ISSUE THREAD

**Issue by nosilver4u** [joeyates/imap-backup#62] opened 2019-01-04 23:11 UTC
I just moved my org to Gsuite, and I've been using imap-backup for quite a while with no issues on the old system.
So today I went to update it to pull mail from the live account on Gsuite, and it keeps giving me fits about invalid credentials.
First, I received an email from Google that they had blocked it. Fair enough, I looked at your instructions, enabled 2-factor auth, then generated an App password for imap-backup, and entered that into the configs.
Now it still says invalid credentials, and Google isn't saying anything about blocking the attempts.

Here's the output with debugging enabled:
`D, [2019-01-04T23:06:43.378829 #5890] DEBUG -- : Running backup of account: abc@xyz
D, [2019-01-04T23:06:43.379046 #5890] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>true}
D, [2019-01-04T23:06:43.446867 #5890] DEBUG -- : Logging in: abc@xyz/xxxxxxxxxxxxxxxxxxx
/usr/lib/ruby/2.3.0/net/imap.rb:1196:in 'get_tagged_response':  Invalid credentials (Failure)
(Net::IMAP::NoResponseError)
	from /usr/lib/ruby/2.3.0/net/imap.rb:1250:in 'block in send_command'
	from /usr/lib/ruby/2.3.0/monitor.rb:214:in 'mon_synchronize'
	from /usr/lib/ruby/2.3.0/net/imap.rb:1232:in 'send_command'
	from /usr/lib/ruby/2.3.0/net/imap.rb:436:in 'login'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:58:in 'imap'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:41:in 'run_backup'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/bin/imap-backup:70:in 'block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:19:in 'block in each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:17:in 'each'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:17:in 'each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.3.0/bin/imap-backup:69:in '<top (required)>'
	from /usr/local/bin/imap-backup:22:in 'load'
	from /usr/local/bin/imap-backup:22:in '<main>'`

**Comment by joeyates** [comment] 2019-01-05 16:15
Sorry to hear about the problem.

imap-backup has always worked in the past with GSuite, but things may have changed. Using the app password is what should work.

I'll set it up for a GSuite account and see what I can find out.

**Comment by paulgessinger** [comment] 2019-01-07 09:43
For what it's worth, I'm using G Suite, and the backup works without problems. I have 2FA enabled and use an app specific password.

**Comment by joeyates** [comment] 2019-01-07 16:55
I think the problem is OS related. Closing in favour of #57

**Closed by joeyates** 2019-01-07 16:55 UTC
