### ISSUE TITLE
Imap-backup

### ISSUE THREAD

**Issue by steowens** [joeyates/imap-backup#27] opened 2015-02-21 06:15 UTC
Unable to get folders list.  it doesn't work with godaddy accounts.  It can't get the folders list.

**Comment by joeyates** [comment] 2015-02-21 14:41
Hello.

Unfortunately, I don't have configuration info for GoDaddy.

To get this working, you'll need to set the 'server' entry for GoDaddy's email servers in `imap-backup setup`. Once you've done that, try 'test connection'.

If that works, great - send me the server entry and I will add it to the list of known configurations.

If it doesn't work, you'll need to edit ~/.imap-backup/config.json and set server_options, to indicate things like the port that GoDaddy expects.

**Comment by steowens** [comment] 2015-02-24 22:23
{
  "accounts": [
    {
      "username": "xxx@xxx.com",
      "password": "xxxxxxxxxx",
      "local_path": "/Users/xxxxxx/.imap-backup/xxx_xxx.com",
      "folders": [
          {"name": "inbox"},
          {"name": "INBOX"},
          {"name": "Sent Items"}
      ],
      "server": "imap.secureserver.net"
    }
  ],
  "debug": true
}

**Comment by steowens** [comment] 2015-02-24 22:25
You don't do anything to throttle do you?  I am noticing it takes exactly 36 seconds per email message to download.  Godaddy swears up and down that they are  not throttling on their end, in spite of the fact that traceroutes get hung up inside their domain.

**Comment by joeyates** [comment] 2015-02-25 08:53
No, imap-backup does not do any throttling.

If it's downloading with the config you posted, then GoDaddy is using port 993 over SSL. The problem is that GD handles a myriad of domains, so I can't really add auto setup.

**Comment by joeyates** [comment] 2015-02-25 08:54
I'll close this issue as it looks like the connection is now working.

**Closed by joeyates** 2015-02-25 08:54 UTC

**Comment by steowens** [comment] 2015-02-25 22:27
Is there any way to get increased logging to detail the timing of the messaging going back and forth?  The logging provided is not as informative as it could be.

**Comment by joeyates** [comment] 2015-02-25 22:45
Currently, with debug logging enabled, you get a timestamp when each message download completes along with the number of bytes in the message body. I think that should be enough for most people's use.

If you need more detailed information, I think this could be dealt with in two ways:
* you could use the existing version, but monitor the "shape" of network traffic via wireshark or other similar network analysis tools,
* otherwise, I'm always willing to discuss pull requests :-)

**Comment by steowens** [comment] 2015-02-26 00:27
Unfortunately my Ruby foo is not that good.  I would probably screw up your code base.
