### ISSUE TITLE
Copy interruption at failing account

### ISSUE THREAD

**Issue by Rudiberto** [joeyates/imap-backup#148] opened 2023-02-13 11:50 UTC
When I Friday changed the password of my account, I forgot to change it also in imap-backup. The day after, I noticed that the backup stopped at this account and did not go further.
Does that mean, that the backups after the failing account has not been done? If so, can I do anything to avoid, that backups after a failing account, are not created?
Since I immediately fixed the problem, I can not see by myself, when the last backup has been done. If so, can I do anything to avoid, that backups after a failing account, are not created?

**Comment by joeyates** [comment] 2023-02-17 08:44
Hi @Rudiberto 

If your backup is interrupted, when it starts again, all messages on the server that have not yet been backed up will be downloaded.

If there were messages that arrived in the period that backup was not working and were deleted (by you or others), then, obviously those messages will not be backed up.

If you want to check what, if anything, is missing, use the `imap-backup local` commands (`imap-backup local accounts`, `imap-backup local folders` and `imap-backup local list`) to check the state of you local backup and compare it to what's present online.

**Comment by Rudiberto** [comment] 2023-02-17 09:23
The reason for the question is, if it would be possible, not to interrupt the whole backup procedure, when one account fails, but go on with the next working item.
The actual behavior lets fail the whole row, if the first account fails, even when the others would work fine. Now I'm thinking about separate instances of imap-backup with only one account for each.

**Comment by joeyates** [comment] 2023-02-18 14:07
Hi @Rudiberto

Sorry, I didn't understand your problem. What I think is the problem is that an error while running the backup on one account stops the whole backup process, so other accounts do not get backed up.

I've now fixed this and will publish a new version later today.

**Comment by joeyates** [comment] 2023-02-18 15:39
Released as version 9.1.0

**Closed** 2023-02-18 15:41 UTC
