### ISSUE TITLE
failures are silent when they should be noisy, and don't catch an obvious error

### ISSUE THREAD

**Issue by jvanasco** [joeyates/imap-backup#34] opened 2017-01-28 03:21 UTC
First off a HUGE thank-you. My provider just decided that their "unlimited" policy would now be "incredibly limited" and gave me 48hours notice that they're deleting my entire email account... of 17 years.  Your package is letting me clone to my linode 10x faster than into my home.

The errors I encountered happened when I set `imap-backup` to archive to a custom location    (it's a mounted partition)

    {"accounts": [{"username: "email@example.com"
                   "local_path: "/mounts/datavolume_2/imap-backup/email@example.com",
                   }
                  ]
     }

The error is related to the existence of the folder "/mounts/datavolume_2/imap-backup/email@example.com"

I only had the parent folder created:  /mounts/datavolume_2/imap-backup/

That caused the system to apparently hang and do nothing.  I switched the "debug" option on and I saw everything being downloaded, but this line was popping up...

    . No such file or directory @ rb_sysopen - /mounts/datavolume_2/imap-backup/email@example.com/INBOX.mbox
    
    
After I ran `mkdir /mounts/datavolume_2/imap-backup/email@example.com` I got this exception raised:

    /var/lib/gems/2.3.0/gems/imap-backup-1.1.0/lib/imap/backup/utils.rb:11:in `check_permissions': Permissions on '/mounts/datavolume_2/imap-backup/email@example.com' should be 0700, not 0755 (RuntimeError)
    
So there are a few issues:

1. The package should either check for existence of "/mounts/datavolume_2/imap-backup/email@example.com" when it starts (and try to make it if it fails). The package will raise a fatal exception if the folder doesn't have the right permissions (good!) but passes silently if it doesn't.  It doesn't even log that info in debug mode.

2. If the package can't write to a folder, it currently just does a debug stream message and keeps going.  Unless debugging is turned on, one would never know.  IMHO this should definitely log to the STDOUT, and it should probably have a config option to raise a fatal exception too (perhaps by default, then let people turn that off?  allowing this to continue but logging errors would be good for automated backups).

I'm sorry I can't offer a PR.  I haven't touched Ruby in years (I'm mostly Python) and it getting back up to speed to fix this and write tests is too much. 

anyways, thanks for this package.  you're a lifesaver.

**Comment by joeyates** [comment] 2017-01-28 20:42
Thanks for opening the issue, I agree with the points you raise.

I'll have a look at this asap.

**Comment by joeyates** [comment] 2017-08-20 09:34
I've released an update which handles directory creation in more or less the way you outline in (1).
So, I believe the issue is now fixed.

**Closed by joeyates** 2017-08-20 09:34 UTC
